baseURL = "https://www.recuerdame-nightcitynights.com"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Recuerdame"
defaultContentLanguage = "es"
[Languages.es]
contentDir = "content/spanish"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "es"
languageName = "Es"
weight = 1
[[Languages.es.menu.main]]
name = "Historia"
pre = "#"
url = "historia"
weight = 1
[[Languages.es.menu.main]]
name = "Equipo"
pre = "#"
url = "team"
weight = 2
[[Languages.es.menu.main]]
name = "Social"
pre = "#"
url = "social"
weight = 4
[params]
author = " - "
description = "Recuerdame - campaña one shot para Salvación de Carisma basada en el mundo de Cyberpunk"
google_analytics_id = ""
logo = "images/logo-rmb.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo-rmb.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
